#ifndef _GLOBALS_H_
#define _GLOBALS_H_

//DEFINE MOTORS:
#define BALL_INTAKE_MTR 1

#define DRIVE_LEFT_A_MTR 2

#define CATAPULT_A_MTR 3      // Power Expander A
#define DRIVE_LEFT_B_MTR 4    // Power Expander B

#define DRIVE_LEFT_C_MTR 5
#define DRIVE_RIGHT_C_MTR 6

#define DRIVE_RIGHT_B_MTR 7 // Power Expander C
#define CATAPULT_B_MTR 9   // Power Expander D

#define DRIVE_RIGHT_A_MTR 8

#define DESCORER_MTR 10

//DEFINE ANALOG SENSORS

#define CATAPULT_POT 1

//DEFINE DIGITAL SENSORS
#define DESCORER_ENC_TOP 1
#define DESCORER_ENC_BOT 2

#define RIGHT_ENC_TOP 3
#define RIGHT_ENC_BOT 4

#define LEFT_ENC_TOP 5
#define LEFT_ENC_BOT 6

#define BACK_ENC_TOP 7
#define BACK_ENC_BOT 8

//CATAPULT
#define CATAPULT_UP_POS 0
#define CATAPULT_DOWN_POS 2000
#define CATAPULT_FIRE_POS 3000

#define CATAPULT_INTEGRAL_RANGE 100
#define CATAPULT_KP 1
#define CATAPULT_KI 1

//DESCORER
#define DESCORER_POWER 110

#define DESCORER_MAX 200
#define DESCORER_MIN 200

#define DESCORER_KP 1

//BALL INTAKE
#define BALL_INTAKE_POWER 110

//POSITION TRACKING
#define TICKS_TO_2INCH 2.75 / 360

#define LEFT_TRACK_OFFSET 3
#define RIGHT_TRACK_OFFSET 3
#define BACK_TRACK_OFFSET 3

#define ANGLE_DEADBAND 0.01

#define MAX_DRIVE_VEL 100

#define DRIVE_KP 0.5


#endif // _GLOBALS_H_
