#ifndef _GLOBAL_H_
#define _GLOBAL_H_

//DEFINE MOTORS:
#define BALL_INTAKE_MTR 1
#define FLYWHEEL_A_MTR 2
#define DRIVE_LEFT_A_MTR 3 // PE
#define DRIVE_LEFT_B_MTR 4 // PE
#define DRIVE_LEFT_C_MTR 5
#define DRIVE_RIGHT_C_MTR 6
#define DRIVE_RIGHT_B_MTR 7 // PE
#define DRIVE_RIGHT_A_MTR 8 // PE
#define FLYWHEEL_B_MTR 9
#define DESCORER_MTR 10

//DEFINE ANALOG SENSORS

//DEFINE DIGITAL SENSORS:
#define FW_ENC_TOP 1
#define FW_ENC_BOT 2

#define DESCORER_ENC_TOP 1
#define DESCORER_ENC_BOT 2

//DEFINE GLOBAL VARS
int runTime;

//DESCORER DEFINITIONS
#define DESCORER_POWER 110

#define DESCORER_MAX 200
#define DESCORER_MIN 200

#define DESCORER_KP 1

//flywheel DEFINITIONS

#define FLYWHEEL_KP 0.5

//BALL INTAKE DEFINITIONS
#define BALL_INTAKE_POWER 110


/*
//DEFINE MOTORS:
#define BALL_INTAKE_MTR

#define DRIVE_LEFT_A_MTR

#define CATAPULT_A_MTR      // Power Expander A
#define DRIVE_LEFT_B_MTR    // Power Expander B

#define DRIVE_LEFT_C_MTR
#define DRIVE_RIGHT_C_MTR

#define DRIVE_RIGHT_B_MTR // Power Expander C
#define CATAPULT_B_MTR  // Power Expander D

#define DRIVE_RIGHT_A_MTR

#define DESCORER_MTR

//DEFINE ANALOG SENSORS

#define CATAPULT_POT

//DEFINE DIGITAL SENSORS
#define DESCORER_ENC_TOP
#define DESCORER_ENC_BOT

#define DESCORER_POWER

#define DESCORER_MAX
#define DESCORER_MIN

#define DESCORER_KP


#define CATAPULT_UP_POS
#define CATAPULT_DOWN_POS
#define CATAPULT_FIRE_POS

#define CATAPULT_INTEGRAL_RANGE
#define CATAPULT_KP
#define CATAPULT_KI


#define BALL_INTAKE_POWER
*/
#endif // _GLOBAL_H_
